apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: addition-service
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: addition-service
    spec:     # pod spec                  
      containers: 
      - name: addition-service
        image: us.icr.io/usf-ngm/addition_service # image we pushed
        ports:
        - containerPort: 3001